name: publish-js-doc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - uses: codevise/sassdoc-action@master
      with:
        output: ./docs/theme
        input: ./src
        
          
    - uses: codevise/documentation-js-action@master
      with:
        output: ./docs/js
        input: ./src
        github: true
        config: ./documentation.yml
        theme: pageflow-documentation-js-theme
        themePackage: codevise/pageflow-documentation-js-theme#master
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
    
