name: publish-js-doc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build
      run: |
        npm install documentation
        node_modules/.bin/documentation build -f html -o docs src/index.js
        
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
