name: publish-js-doc

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - uses: codevise/sassdoc-action@master
      with:
        output: ./docs/<branch>/theme
        input: ./src
        theme: pageflow
        themePackage: tf/sassdoc-theme-pageflow#fs-extra
        
    - uses: codevise/documentation-js-action@master
      with:
        output: ./docs/${{ github.ref }}/js
        input: ./src
        github: true
        config: ./documentation.yml
        theme: pageflow-documentation-js-theme
        themePackage: codevise/pageflow-documentation-js-theme#master
        
    - name: Deploy
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
        bash ./entrypoint.sh
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
        SCRIPT_MODE: true
  
    
